### ISSUE TITLE
Use `with_context(cx)` ID?

### ISSUE THREAD

**Issue by bbigras** [asaaki/opentelemetry-surf#3]
## Question/Suggestion

In this code:

```rust
    let tracer = global::tracer("(child)");
    let span = tracer.start("fetch");
    let cx = opentelemetry::Context::current_with_value(span);

    let res: Status = http_client
        .get(&url)
        .recv_json()
        .with_context(cx)
        .await?;
```

Is it possible to make the sent parent trace be the same as `let span = tracer.start("fetch")`?

**Comment by asaaki** [comment]
As far as the current code goes, before sending a request the middleware tries to extract trace info from a request object or uses the current context instead.

So in general there a 3 stages in the middleware:
1. extract possible parent trace from request headers and construct context **OR** use the current context
2. add own trace data into request
3. add trace info to response (in case you want/need to process it further)

For most standard cases your get request should use the parent context already (assuming everything happens within the same thread and the request object does not have any tracing headers).

Is that not the case for you?

I'll probably need to check the front-server of the otel tide examples, using this repo instead of the custom code, but logically there is no difference and I had nested spans for the same trace across both the tide and surf parts.

https://github.com/asaaki/opentelemetry-tide/blob/5116fae2b624b6c9fc967d3d4c60aa63f228bd69/examples/front-server.rs#L54-L95

**Comment by asaaki** [comment]
As far as I understand the question, otel surf does what was asked.
For playing around with both crates together, you can check out https://github.com/asaaki/surfing-the-tide, make requests and check jaeger query UI, everything should be nicely tied together in the same traces.

If I misunderstood the question, please feel free to open/comment with more clarifications.
